[build-system]
requires = ["setuptools>=58", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/stable/reference/reference.html#ini-options-ref
testpaths = ["tests"]
pythonpath = ["."]
verbosity_assertions = 2
